# Test against the latest version of this Node.js version
environment:
  nodejs_version: "6"

# Do not build tags (prevents double builds)
skip_tags: true

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # Run batch
  - ./build.win.bat

# Add caching to speed up build
cache:
  - "%LOCALAPPDATA%\\Yarn"

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

on_finish:
  - echo %cd%
  - rd /s /q ..\LaserWeb4\node_modules

# Don't actually build.
build: off

# Add some artifacts, these are things we want to keep
artifacts:
  - path: dist\*
    name: LocalDist

# Deploy to the cloud
deploy:
  release: $(appveyor_build_version)
  description: 'LaserWeb for Mac and PC (`$(TARGET_UI_BRANCH)`).\n\n>$(GIT_LOGS)'
  provider: GitHub
  auth_token:
    secure:  yGBLBhF4ye007oEUaBk0r+IQD5BczKPVQ4JSflT3FZrBb0kFyU6QsyF86FXGE+Vi
  artifact: LocalDist            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master               # release from master branch only
